# SPDX-FileCopyrightText: 2021-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

name: Transifex

on:
  pull_request:
    branches:
      - main
      - stable*

permissions:
  contents: read

concurrency:
  group: transifex-approve-merge-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  auto-approve-merge:
    if: github.event.pull_request.user.login == 'transifex-integration[bot]'
    runs-on: ubuntu-latest
    permissions:
      # for hmarr/auto-approve-action to approve PRs
      pull-requests: write

    steps:
      - name: Disabled on forks
        if: ${{ github.event.pull_request.head.repo.full_name != github.repository }}
        run: |
          echo 'Can not approve PRs from forks'
          exit 1

      # GitHub actions bot approve
      - uses: hmarr/auto-approve-action@f0939ea97e9205ef24d872e76833fa908a770363 # v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: pascalgn/automerge-action@v0.16.4
        env:
          MERGE_DELETE_BRANCH: true
          MERGE_LABELS: ''
          MERGE_RETRIES: 6
          MERGE_RETRY_SLEEP: 30000
          GITHUB_TOKEN: ${{ secrets.COMMAND_BOT_PAT }}
